export const ExamActionTypes = {
  FETCH_EXAMS_START: 'FETCH_EXAMS_START',
  FETCH_EXAMS_SUCCESS: 'FETCH_EXAMS_SUCCESS',
  FETCH_EXAMS_FAILURE: 'FETCH_EXAMS_FAILURE',
  CREATE_EXAM_START: 'CREATE_EXAM_START',
  CREATE_EXAM_SUCCESS: 'CREATE_EXAM_SUCCESS',
  CREATE_EXAM_FAILURE: 'CREATE_EXAM_FAILURE'
};
