export const TryoutActionTypes = {
  ADD_NEW_TRYOUT: 'ADD_NEW_TRYOUT',
  UPDATE_TRYOUT: 'UPDATE_TRYOUT',
  FETCH_TRYOUT_START: 'FETCH_TRYOUT_START',
  FETCH_TRYOUT_SUCCESS: 'FETCH_TRYOUT_SUCCESS',
  FETCH_TRYOUT_FAILURE: 'FETCH_TRYOUT_FAILURE'
};
